/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e3e4",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#4cd7f6",
        surface: "#f8f9fa",
        "inverse-primary": "#c3c0ff",
        background: "#f8f9fa",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#001f26",
        "primary-fixed": "#e2dfff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "secondary-container": "#57dffe",
        "tertiary-fixed": "#ffdbcc",
        tertiary: "#7e3000",
        "surface-container-high": "#e7e8e9",
        "inverse-surface": "#2e3132",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f5",
        "on-surface-variant": "#464555",
        "on-secondary-container": "#006172",
        "on-background": "#191c1d",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1d",
        secondary: "#00687a",
        "on-tertiary-fixed": "#351000",
        "primary-container": "#4f46e5",
        primary: "#3525cd",
        "on-primary-fixed": "#0f0069",
        "secondary-fixed": "#acedff",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "tertiary-container": "#a44100",
        "inverse-on-surface": "#f0f1f2",
        "tertiary-fixed-dim": "#ffb695",
        "surface-bright": "#f8f9fa",
        "outline-variant": "#c7c4d8",
        "surface-tint": "#4d44e3",
        "on-primary-container": "#dad7ff",
        "on-primary-fixed-variant": "#3323cc",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-container": "#ffd2be",
        outline: "#777587",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
